"""add validation_rule_definitions table

Revision ID: 9e757494df99
Revises: da4f88dca183
Create Date: 2026-08-24 18:27:25.606888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e757494df99'
down_revision: Union[str, Sequence[str], None] = 'da4f88dca183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_rule_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('field_path', sa.String(length=256), nullable=True),
    sa.Column('description_nl', sa.Text(), nullable=True),
    sa.Column('condition_cel', sa.Text(), nullable=True),
    sa.Column('applies_when_cel', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('message_pass', sa.Text(), nullable=True),
    sa.Column('message_fail', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('reviewer_identity', sa.String(length=256), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_rule_definitions')
    # ### end Alembic commands ###
