"""add document segmentation columns

Revision ID: f44945f5a67d
Revises: c6efe8aab630
Create Date: 2026-08-23 18:02:35.708356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44945f5a67d'
down_revision: Union[str, Sequence[str], None] = 'c6efe8aab630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parent_document_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('page_end', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'documents', ['parent_document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'page_end')
    op.drop_column('documents', 'page_start')
    op.drop_column('documents', 'parent_document_id')
    # ### end Alembic commands ###
